// Generates theme/alphatrade/scss/post/_icons.scss with only the Phosphor icons used in the code.
// Usage: cd tools && npm install && npm run icons
import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const phosphor = join(root, 'tools', 'node_modules', '@phosphor-icons', 'web');

const scan = (dir, out = []) => {
    for (const name of readdirSync(dir)) {
        const path = join(dir, name);
        if (statSync(path).isDirectory()) {
            if (!['node_modules', 'fonts', 'pix', '.git'].includes(name)) {
                scan(path, out);
            }
        } else if (/\.(php|mustache|js)$/.test(name)) {
            out.push(path);
        }
    }
    return out;
};

const used = new Set();
for (const file of [...scan(join(root, 'theme')), ...scan(join(root, 'local'))]) {
    for (const match of readFileSync(file, 'utf8').matchAll(/\bph-([a-z0-9]+(?:-[a-z0-9]+)*)\b/g)) {
        if (match[1] !== 'fill') {
            used.add(match[1]);
        }
    }
}

const codepoints = (style) => {
    const css = readFileSync(join(phosphor, 'src', style, 'style.css'), 'utf8');
    const map = new Map();
    for (const match of css.matchAll(/\.ph(?:-fill)?\.ph-([a-z0-9-]+):before\s*\{\s*content:\s*"\\([0-9a-f]+)";/g)) {
        map.set(match[1], match[2]);
    }
    return map;
};
const regular = codepoints('regular');
const fill = codepoints('fill');

const missing = [...used].filter((name) => !regular.has(name));
if (missing.length) {
    console.error('Unknown Phosphor icons: ' + missing.join(', '));
    process.exit(1);
}

let scss = '// Generated by tools/build-icons.mjs - do not edit by hand.\n';
scss += '// Phosphor Icons (MIT) subset: ' + used.size + ' icons, regular + fill.\n\n';
scss += '.ph, .ph-fill {\n    display: inline-block;\n    font-style: normal;\n    font-weight: normal;\n    font-variant: normal;\n';
scss += '    line-height: 1;\n    text-transform: none;\n    speak: never;\n    -webkit-font-smoothing: antialiased;\n    -moz-osx-font-smoothing: grayscale;\n}\n';
scss += '.ph { font-family: "Phosphor" !important; }\n.ph-fill { font-family: "Phosphor-Fill" !important; }\n\n';
for (const name of [...used].sort()) {
    scss += `.ph.ph-${name}:before { content: "\\${regular.get(name)}"; }\n`;
    if (fill.has(name)) {
        scss += `.ph-fill.ph-${name}:before { content: "\\${fill.get(name)}"; }\n`;
    }
}
writeFileSync(join(root, 'theme', 'alphatrade', 'scss', 'post', '_icons.scss'), scss);
console.log(`_icons.scss: ${used.size} icons`);
